language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
script: xcodebuild test -project ziphy.xcodeproj -scheme ziphy -sdk iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=ziphy
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
